In [1]:
import numpy as np

# More Detailed NumPy Cheatsheet


# Array creation
a = np.array([1, 2, 3])                        # 1D array
b = np.zeros((2, 3))                           # 2x3 array of zeros
c = np.ones((3, 2), dtype=int)                 # 3x2 array of ones (int)
d = np.eye(3)                                  # 3x3 identity matrix
e = np.arange(0, 10, 2)                        # array([0, 2, 4, 6, 8])
f = np.linspace(0, 1, 5)                       # 5 values from 0 to 1
g = np.random.rand(2, 2)                       # 2x2 array of random floats in [0, 1)
h = np.random.randint(0, 10, (3, 3))           # 3x3 array of random ints in [0, 10)
i = np.full((2, 2), 7)                         # 2x2 array filled with 7

# Array properties
a.shape                                        # Shape of array
a.ndim                                         # Number of dimensions
a.size                                         # Number of elements
a.dtype                                        # Data type
a.itemsize                                     # Size of each element in bytes
a.nbytes                                       # Total bytes consumed

# Indexing and slicing
arr = np.arange(10)
arr[2:5]                                       # Slicing
arr[::-1]                                      # Reverse array
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d[1, 2]                                    # Element at row 1, col 2
arr2d[:, 1]                                    # All rows, column 1
arr2d[0, :]                                    # Row 0, all columns

# Boolean indexing & fancy indexing
mask = arr > 5
arr[mask]                                      # Elements greater than 5
arr[[2, 4, 6]]                                 # Elements at indices 2, 4, 6

# Basic operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
x + y                                          # Elementwise addition
x * y                                          # Elementwise multiplication
x / y                                          # Elementwise division
x ** 2                                         # Elementwise power
np.dot(x, y)                                   # Dot product
np.sum(x)                                      # Sum of elements
np.mean(x)                                     # Mean
np.std(x)                                      # Standard deviation
np.max(x), np.min(x)                           # Max and min
np.argmax(x), np.argmin(x)                     # Indices of max and min

# Reshaping and stacking
arr3 = np.arange(6).reshape((2, 3))            # Reshape to 2x3
np.vstack([x, y])                              # Vertical stack
np.hstack([x, y])                              # Horizontal stack
np.concatenate([x, y])                         # Concatenate arrays

# Transpose and flatten
arr3.T                                         # Transpose
arr3.flatten()                                 # Flatten to 1D

# Aggregation along axes
mat = np.array([[1,2,3],[4,5,6]])
np.sum(mat, axis=0)                            # Sum over columns
np.sum(mat, axis=1)                            # Sum over rows
np.mean(mat, axis=0)                           # Mean over columns

# Broadcasting
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
a + b                                          # Broadcasting addition

# Useful functions
np.unique(arr)                                 # Unique elements
np.sort(arr)                                   # Sort array
np.argsort(arr)                                # Indices that would sort array
np.where(arr > 5)                              # Indices where condition is True
np.clip(arr, 2, 8)                             # Limit values to [2, 8]
np.cumsum(arr)                                 # Cumulative sum
np.diff(arr)                                   # Discrete difference

# Linear algebra
A = np.array([[1, 2], [3, 4]])
np.linalg.inv(A)                               # Inverse
np.linalg.det(A)                               # Determinant
np.linalg.eig(A)                               # Eigenvalues and eigenvectors

# Save and load
np.save('my_array.npy', arr)
arr_loaded = np.load('my_array.npy')

# Miscellaneous
np.set_printoptions(precision=3, suppress=True) # Print options

In [2]:
# NumPy Delete Cheatsheet

# Delete elements from a 1D array by index
arr1 = np.array([0, 1, 2, 3, 4, 5])
arr1_deleted = np.delete(arr1, [1, 3])  # Deletes elements at indices 1 and 3

# Delete rows or columns from a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Delete row at index 0
arr2_row_deleted = np.delete(arr2, 0, axis=0)

# Delete column at index 1
arr2_col_deleted = np.delete(arr2, 1, axis=1)

# Delete multiple rows or columns
arr2_multi_row_deleted = np.delete(arr2, [0, 2], axis=0)
arr2_multi_col_deleted = np.delete(arr2, [0, 2], axis=1)

# Delete using boolean mask (flattened indices)
mask = np.array([True, False, True, False, True, False])
arr1_mask_deleted = np.delete(arr1, np.where(mask)[0])

# Note: np.delete does not modify the original array, it returns a new array.

In [3]:
print(arr1_mask_deleted)

[1 3 5]


In [4]:
# NumPy Delete, Append, and Insert Cheatsheet

# --- Delete ---
# Delete elements from a 1D array by index
arr = np.array([0, 1, 2, 3, 4, 5])
deleted = np.delete(arr, [1, 3])  # Deletes elements at indices 1 and 3

# Delete rows or columns from a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_deleted = np.delete(arr2d, 0, axis=0)      # Delete row at index 0
col_deleted = np.delete(arr2d, 1, axis=1)      # Delete column at index 1

# --- Append ---
# Append values to the end of a 1D array
appended = np.append(arr, [6, 7])

# Append values to a 2D array (must match shape except for axis)
row_appended = np.append(arr2d, [[10, 11, 12]], axis=0)  # Add new row
col_appended = np.append(arr2d, [[10], [11], [12]], axis=1)  # Add new column

# --- Insert ---
# Insert values into a 1D array at given index
inserted = np.insert(arr, 2, 99)  # Insert 99 at index 2

# Insert values into a 2D array
row_inserted = np.insert(arr2d, 1, [10, 11, 12], axis=0)  # Insert row at index 1
col_inserted = np.insert(arr2d, 2, [10, 11, 12], axis=1)  # Insert column at index 2

# Note: All these functions return a new array and do not modify the original array.

In [5]:
# NumPy Diagonal Cheatsheet (5x5 integer array example)

arr5 = np.arange(1, 26).reshape(5, 5)
print("arr5:\n", arr5)

# Get the main diagonal
main_diag = np.diag(arr5)  # array([ 1, 7, 13, 19, 25])
print("Main diagonal:", main_diag)

# Get the diagonal above the main (k=1) and below (k=-1)
diag_above = np.diag(arr5, k=1)   # array([ 2, 8, 14, 20])
diag_below = np.diag(arr5, k=-1)  # array([ 6, 12, 18, 24])
print("Diagonal above main:", diag_above)
print("Diagonal below main:", diag_below)

# Create a 5x5 array with a given diagonal
v = np.array([10, 20, 30, 40, 50])
diag_matrix = np.diag(v)
print("Matrix with v on main diagonal:\n", diag_matrix)

# Set the diagonal of an existing array (square only)
arr5_copy = arr5.copy()
np.fill_diagonal(arr5_copy, 0)
print("arr5 with main diagonal set to 0:\n", arr5_copy)

# Note: np.diag and np.fill_diagonal do not modify the original array unless you use .copy()

arr5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Main diagonal: [ 1  7 13 19 25]
Diagonal above main: [ 2  8 14 20]
Diagonal below main: [ 6 12 18 24]
Matrix with v on main diagonal:
 [[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]
arr5 with main diagonal set to 0:
 [[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [21 22 23 24  0]]


In [6]:
# NumPy Boolean Indexing, Set Operations, and Sorting Cheatsheet

# --- Boolean Indexing ---
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mask = arr > 5
filtered = arr[mask]                # array([ 6,  7,  8,  9, 10])
arr[arr % 2 == 0]                   # Even numbers: array([ 2,  4,  6,  8, 10])
arr[(arr > 3) & (arr < 8)]          # array([4, 5, 6, 7])

# --- Set Operations ---
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
np.intersect1d(a, b)                # array([3, 4])
np.union1d(a, b)                    # array([1, 2, 3, 4, 5, 6])
np.setdiff1d(a, b)                  # array([1, 2]) (in a but not in b)
np.setdiff1d(b, a)                  # array([5, 6]) (in b but not in a)
np.setxor1d(a, b)                   # array([1, 2, 5, 6]) (in a or b but not both)
np.in1d(a, b)                       # array([False, False,  True,  True])

# --- Sorting ---
unsorted = np.array([5, 2, 9, 1])
sorted_arr = np.sort(unsorted)      # array([1, 2, 5, 9])
sort_indices = np.argsort(unsorted) # array([3, 1, 0, 2])
unsorted[sort_indices]              # array([1, 2, 5, 9])

# Sort along axis for 2D arrays
arr2d = np.array([[8, 4, 1], [3, 7, 5]])
np.sort(arr2d, axis=0)              # Sort each column
np.sort(arr2d, axis=1)              # Sort each row

# Unique and counts
unique_vals = np.unique(arr)        # Unique values in arr
vals, counts = np.unique(arr, return_counts=True)  # Unique values and their counts

/tmp/ipykernel_22465/1684199958.py:18: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a, b)                       # array([False, False,  True,  True])
